# -*- coding: utf-8 -*-
"""Builds the MyGym User Guide body PDF (no cover - cover merged separately)."""
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Image,
    Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

BASE = r"D:\projects\my_gym\user guide"
SHOTS = os.path.join(BASE, "screenshots")

# ---- Fonts (local Windows fonts) ----
FONTS = r"C:\Windows\Fonts"
pdfmetrics.registerFont(TTFont("Calibri", os.path.join(FONTS, "calibri.ttf")))
pdfmetrics.registerFont(TTFont("Calibri-Bold", os.path.join(FONTS, "calibrib.ttf")))
registerFontFamily("Calibri", normal="Calibri", bold="Calibri-Bold")

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
ACCENT       = colors.HexColor('#278eb0')
TEXT_PRIMARY = colors.HexColor('#1d1f20')
TEXT_MUTED   = colors.HexColor('#6e767a')
BG_SURFACE   = colors.HexColor('#d4dade')
BG_PAGE      = colors.HexColor('#eef0f1')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = colors.HexColor('#e9edef')

PAGE_W, PAGE_H = A4
MARGIN = 62
CONTENT_W = PAGE_W - 2 * MARGIN

# ---- Styles ----
h1 = ParagraphStyle("h1", fontName="Calibri-Bold", fontSize=19, leading=24,
                    textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=8)
h2 = ParagraphStyle("h2", fontName="Calibri-Bold", fontSize=13, leading=17,
                    textColor=TEXT_PRIMARY, spaceBefore=12, spaceAfter=5)
body = ParagraphStyle("body", fontName="Calibri", fontSize=10.5, leading=15,
                      textColor=TEXT_PRIMARY, spaceAfter=6)
bullet = ParagraphStyle("bullet", parent=body, leftIndent=14, bulletIndent=4, spaceAfter=3)
step = ParagraphStyle("step", parent=body, leftIndent=16, spaceAfter=4)
caption = ParagraphStyle("caption", fontName="Calibri", fontSize=8.5, leading=11,
                         textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=4)
tip = ParagraphStyle("tip", parent=body, fontSize=9.5, leading=13.5,
                     textColor=TEXT_PRIMARY, backColor=BG_PAGE,
                     borderPadding=6, spaceBefore=4, spaceAfter=8)
toc_item = ParagraphStyle("toc", fontName="Calibri", fontSize=11, leading=20, textColor=TEXT_PRIMARY)
toc_head = ParagraphStyle("toch", fontName="Calibri-Bold", fontSize=15, leading=20,
                          textColor=TEXT_PRIMARY, spaceBefore=6, spaceAfter=8)

def H1(n, text):
    return Paragraph(f"{n}.  {text}", h1)

def B(text):
    return Paragraph(text, bullet, bulletText="\u2022")

def S(text):
    return Paragraph(f"<b>{text}</b>", step)

def img_cell(name, width=150):
    path = os.path.join(SHOTS, name)
    # 414x880 source -> proportional height
    h = width * 880.0 / 414.0
    return Image(path, width=width, height=h)

def feature_section(num, title, image, caption_text, paragraphs, steps=None, tip_text=None, bullets=None):
    """Side-by-side layout: phone screenshot left, guidance right.

    Heading + table + caption are one KeepTogether unit: a screenshot block is
    over half a page tall, so letting the heading separate strands it at a page
    bottom with nothing after it.
    """
    heading = H1(num, title)
    text_flow = []
    for p in paragraphs:
        text_flow.append(Paragraph(p, body))
    if steps:
        for s_ in steps:
            text_flow.append(S(s_))
    if bullets:
        for b_ in bullets:
            text_flow.append(B(b_))
    if tip_text:
        text_flow.append(Spacer(1, 2))
        text_flow.append(Paragraph(f"<b>Tip:</b> {tip_text}", tip))

    img = img_cell(image)
    cap = Paragraph(caption_text, caption)
    row = [[img, text_flow]]
    t = Table(row, colWidths=[160, CONTENT_W - 160 - 14])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (0, -1), 0),
        ("RIGHTPADDING", (0, 0), (0, -1), 6),
        ("LEFTPADDING", (1, 0), (1, -1), 10),
        ("RIGHTPADDING", (1, 0), (1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    t.hAlign = "CENTER"
    return [KeepTogether([heading, t, cap])]

story = []

# ---- Contents ----
story.append(Paragraph("Contents", toc_head))
toc_rows = [
    ("1", "Getting Started"), ("2", "The Home Screen"), ("3", "Logging a Workout"),
    ("4", "Workout History & Search"), ("5", "Routines: Planning Your Training"),
    ("6", "Progress & Personal Records"), ("7", "Settings & Your Data"),
    ("8", "Google Sheets Backup"), ("9", "Offline Use & Installation"),
    ("10", "Tips & Troubleshooting"),
]
toc_tbl = Table(
    [[Paragraph(f"<b>{n}</b>", toc_item), Paragraph(t, toc_item)] for n, t in toc_rows],
    colWidths=[30, CONTENT_W - 30],
    rowHeights=None,
)
toc_tbl.setStyle(TableStyle([
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("LINEBELOW", (0, 0), (-1, -2), 0.4, BG_SURFACE),
    ("TOPPADDING", (0, 0), (-1, -1), 3),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ("LEFTPADDING", (0, 0), (-1, -1), 2),
]))
toc_tbl.hAlign = "CENTER"
story.append(toc_tbl)
story.append(Spacer(1, 10))
story.append(Paragraph(
    "MyGym is an offline-first workout planner and logger that runs entirely on your device. "
    "Nothing you log leaves your phone unless you turn on the optional Google Sheets backup. "
    "This guide walks through every screen and every feature.", body))
story.append(PageBreak())

# ---- 1. Getting Started ----
story.append(H1(1, "Getting Started"))
story.append(Paragraph(
    "MyGym works fully offline. All workouts, routines and settings live in your browser's "
    "IndexedDB storage on your device - there is no account and no server.", body))
story.append(Paragraph("Install it like an app", h2))
for s_ in [
    "1.  Open <b>my-gym-hammad42.netlify.app</b> in Chrome (Android) or Safari (iPhone).",
    "2.  Android: tap the menu (three dots) and choose <b>Add to Home screen</b>.",
    "3.  iPhone: tap the Share icon, then <b>Add to Home Screen</b>.",
    "4.  Launch it from your home screen from now on - it opens full-screen and works with no signal.",
]:
    story.append(S(s_))
story.append(Paragraph("First launch", h2))
story.append(Paragraph(
    "The app seeds a demo exercise library (21 exercises), three routines (Push, Pull, Legs) and "
    "about six weeks of sample workouts so the charts have something to show. When you are ready "
    "for real training, go to <b>Settings &gt; Clear all logged workouts</b> - your routines and "
    "exercise library are kept.", body))
story.append(Paragraph(
    "<b>Tip:</b> everything is stored on this device. Using a different phone or browser means "
    "starting fresh (or restoring a backup) - see section 8.", tip))

# ---- 2. Home Screen ----
story.extend(feature_section(
    2, "The Home Screen", "01-home-dashboard.png",
    "The Home screen: weekly goal, this week's totals, routines and recent sessions.",
    [
        "Home is your training dashboard. Everything here updates automatically as you log.",
    ],
    bullets=[
        "<b>This Week</b> - sessions completed against your weekly goal, with a progress bar.",
        "<b>Streak badge</b> - consecutive weeks (including the current one) where you hit the goal.",
        "<b>Sets / Volume / Time</b> - this week's totals. Volume counts working sets only; warm-up sets are excluded from volume but still counted as sets.",
        "<b>Start a routine</b> - one tap opens a new workout pre-filled with that routine's plan.",
        "<b>Log a free workout</b> - start an empty workout without a routine.",
        "<b>Recent sessions</b> - your last five workouts at a glance.",
    ],
    tip_text="change your weekly goal in Settings &gt; Preferences (1-14 sessions per week).",
))

# ---- 3. Logging a Workout ----
story.append(KeepTogether([
    H1(3, "Logging a Workout"),
    Paragraph(
        "Tap the big <b>+</b> button, or <b>Log a free workout</b> on Home. Nothing is committed "
        "until you press <b>Save workout</b> - and while you log, everything is auto-saved as a "
        "draft, so switching tabs or locking your screen never loses a set.", body),
]))
story.extend(feature_section(
    "3.1", "Fill in the session", "02-log-workout.png",
    "A workout in progress: live estimated 1RM per set and a running volume total.",
    [
        "Give the workout a name, check the date (defaults to today - future dates are rejected), "
        "and optionally record how long you trained and your body weight.",
        "Tap <b>Add exercise</b> to add a block, then <b>Add set</b> for each set. Every new set "
        "carries forward the previous weight and reps, and starts a rest timer.",
    ],
    bullets=[
        "<b>W button</b> - marks a set as a warm-up. Warm-ups are excluded from volume and personal records.",
        "<b>~1RM</b> - live estimated one-rep max (Epley formula) updates as you type.",
        "<b>Sticky footer</b> - running set count and total volume before you save.",
    ],
    tip_text="decimal weights (82.5) and decimal reps are stored exactly as typed.",
))
story.extend(feature_section(
    "3.2", "The rest timer", "03-rest-timer.png",
    "Adding a set starts the rest countdown (default 90 s).",
    [
        "Adding a set starts a countdown (default 90 seconds - configurable in Settings). It is "
        "deadline-based, so locking your screen or replying to a message does not drift it, and it "
        "keeps counting across screens. When it hits zero the app beeps and vibrates, and if you "
        "were on another tab it resumes and finishes correctly when you come back.",
        "Tap <b>Skip</b> to end it early.",
    ],
))
story.extend(feature_section(
    "3.3", "Never lose a workout", "10-draft-recovery.png",
    "Re-open the Log tab and your unfinished workout is exactly where you left it.",
    [
        "If you navigate away (or the app closes) mid-workout, the Log screen shows a blue banner: "
        "<i>Resumed your unfinished workout - nothing was lost</i>. Continue where you stopped, or "
        "tap <b>Start fresh</b> to discard the draft.",
        "The app also asks for confirmation before leaving a workout that has unsaved content, so "
        "an accidental tab tap is never a scare.",
    ],
    tip_text="the draft is cleared automatically the moment the workout is saved.",
))
story.append(Paragraph(
    "<b>Save workout</b> writes the session and every set in one atomic step. You will see a "
    "confirmation, and the workout appears on Home and in History immediately.", body))

# ---- 4. History ----
story.extend(feature_section(
    4, "Workout History & Search", "04-history-expanded.png",
    "History grouped by day; tap a workout to expand every set.",
    [
        "History lists every session newest-first, grouped by day (Today, Yesterday, then dates). "
        "Each card summarises exercises, sets, volume and duration.",
        "Tap a workout to expand it: every exercise shows its sets as chips "
        "(weight x reps, blue = warm-up) plus the best set of the session.",
    ],
    bullets=[
        "<b>Search</b> - the box at the top filters by workout name, exercise name or notes.",
        "<b>Delete session</b> - two-step: tap once, then confirm. Its sets are removed too.",
    ],
))

# ---- 5. Routines ----
story.extend(feature_section(
    5, "Routines: Planning Your Training", "05-routines.png",
    "Each routine shows its plan as sets x reps chips, with edit, archive and start actions.",
    [
        "Routines are your training templates. Each card shows the planned exercises as "
        "<b>sets x reps</b> chips, the day hint, and when you last performed it.",
    ],
    bullets=[
        "<b>Play</b> (orange) - start a workout pre-filled with this plan.",
        "<b>Pencil</b> - edit name, description, day and the exercise plan.",
        "<b>Archive</b> - hide a routine you no longer follow without deleting its history.",
    ],
))
story.extend(feature_section(
    "5.1", "Editing a routine", "06-routine-editor.png",
    "Reorder, re-target or remove exercises; changes apply to future workouts only.",
    [
        "In the editor you can rename the routine, set a day hint, and manage the plan: add "
        "exercises, reorder them with the arrows, remove them, and set target sets and reps per "
        "exercise. Each exercise appears at most once per routine.",
        "Saving only affects <b>future</b> workouts - your logged history is never rewritten.",
    ],
))

# ---- 6. Progress ----
story.extend(feature_section(
    6, "Progress & Personal Records", "07-progress.png",
    "Weekly sessions, volume by muscle group and a per-exercise progression chart.",
    [
        "The Progress tab turns your log into feedback:",
    ],
    bullets=[
        "<b>Sessions per week</b> - the last 8 weeks; bars that hit your goal are highlighted orange.",
        "<b>Volume by muscle group</b> - total tonnage per body part, working sets only.",
        "<b>Exercise progression</b> - pick any exercise to chart your heaviest working set per session.",
        "<b>Personal records</b> - heaviest set and best estimated 1RM (Epley) per exercise, with dates. Warm-ups never count.",
    ],
    tip_text="bodyweight exercises (weight 0) are tracked by reps and never produce a fake 1RM.",
))

# ---- 7. Settings ----
story.extend(feature_section(
    7, "Settings & Your Data", "08-settings-preferences.png",
    "Preferences, the exercise library, and data tools all live in Settings.",
    [
        "<b>Weight unit</b> - switching kg/lb converts every stored weight so your history stays "
        "accurate. The app asks for confirmation and reports how many values it converted.",
        "<b>Weekly goal</b> - 1 to 14 sessions per week; drives Home and the streak.",
        "<b>Rest timer</b> - default countdown when you add a set (15-600 s).",
        "<b>Exercise library</b> - add your own exercises (name, muscle group, equipment). "
        "Exercises used in your log are archived rather than deleted, so history never breaks.",
    ],
))
story.append(Paragraph("Export, import and reset", h2))
for b_ in [
    "<b>Export JSON</b> - downloads a complete backup file. Secrets are stripped automatically.",
    "<b>Import JSON</b> - restores a backup after showing you exactly what it will replace.",
    "<b>Clear all logged workouts</b> - empties sessions and sets; keeps routines and the library.",
    "<b>Reset to demo data</b> - restores the sample content and default preferences (your Google Sheets credentials survive).",
]:
    story.append(B(b_))

# ---- 8. Google Sheets ----
story.extend(feature_section(
    8, "Google Sheets Backup", "09-settings-sheets.png",
    "One-time setup, then your log mirrors into a spreadsheet you own.",
    [
        "The optional Google Sheets backup mirrors every workout into a private spreadsheet on "
        "your own Google account - a readable training log, session summaries, your library and "
        "routines, plus a raw backup you can restore from.",
    ],
    steps=[
        "1.  Settings &gt; Google Sheets Backup &gt; <b>Show setup instructions &amp; Apps Script code</b> &gt; <b>Copy Apps Script code</b>.",
        "2.  Create a blank sheet at <b>sheets.new</b>, then Extensions &gt; Apps Script: delete everything and paste the code.",
        "3.  Change <b>SECRET_KEY</b> in the script to your own password (8+ characters) - until you do, the webhook refuses everything.",
        "4.  Deploy &gt; Manage deployments &gt; edit the existing deployment &gt; Version: New version. Execute as <b>Me</b>, access <b>Anyone</b>.",
        "5.  Back in the app: paste the Web App URL and the same secret, <b>Save</b>, <b>Test</b>, then <b>Sync now</b>.",
    ],
    tip_text="after setup, the header shows a Sheets button for instant manual syncs.",
))
story.append(Paragraph("How syncing behaves", h2))
for b_ in [
    "<b>Auto-sync 2x daily</b> - runs in the background while the app is open and online (toggleable). It never interrupts an active workout.",
    "<b>Load data from sheet (restore)</b> - replaces this device's data with the sheet's backup; your credentials are kept.",
    "<b>Security</b> - the secret key is sent only to authenticate each request. It is never stored in the sheet, never written into exports, and never adopted from an imported backup.",
    "<b>Large logs</b> - uploads are automatically split into chunks, so years of training sync fine.",
]:
    story.append(B(b_))

# ---- 9. Offline & Installation ----
story.append(H1(9, "Offline Use & Installation"))
story.append(Paragraph(
    "MyGym is a PWA: after the first load it is installed on your device and every screen works "
    "with no connection. Log workouts, browse history, check progress and edit routines entirely "
    "offline - sync simply waits until you are online again.", body))
for b_ in [
    "<b>Install once</b> - Add to Home Screen (see section 1); then launch from the icon, not the browser.",
    "<b>Storage protection</b> - the app requests persistent storage on first run so the browser will not evict your data.",
    "<b>Private browsing</b> - incognito windows usually block storage; the app warns you instead of silently losing data.",
    "<b>Updates</b> - new versions are picked up automatically on the next online launch; your data is untouched.",
]:
    story.append(B(b_))

# ---- 10. Tips & Troubleshooting ----
story.append(H1(10, "Tips & Troubleshooting"))
qa = [
    ("Where did my weekly volume go?",
     "Warm-up sets are excluded from volume and records by design. They still count towards your set totals."),
    ("The rest timer did not beep",
     "On iPhone, sound can only start after you have interacted with the page - tap anywhere once. Vibration works on Android."),
    ("I switched kg to lb and numbers changed",
     "That is the data being converted so charts stay correct - it is not a bug. Switch back and confirm to convert again."),
    ("My sheet has someone else's workouts",
     "You restored or synced from a different device. Run Sync now from this device to overwrite the sheet with this device's data."),
    ("Charts show old workouts I don't recognise",
     "That is the demo data from first launch. Clear it in Settings > Clear all logged workouts."),
    ("Can I move my data to a new phone?",
     "Yes - Export JSON on the old device, Import JSON on the new one. Or restore from your Google Sheet backup."),
]
qa_rows = [[Paragraph(f"<b>{q}</b>", body), Paragraph(a, body)] for q, a in qa]
qa_tbl = Table(qa_rows, colWidths=[CONTENT_W * 0.34, CONTENT_W * 0.62])
qa_tbl.setStyle(TableStyle([
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("ROWBACKGROUNDS", (0, 0), (-1, -1), [TABLE_ROW_EVEN, TABLE_ROW_ODD]),
    ("TOPPADDING", (0, 0), (-1, -1), 6),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
]))
qa_tbl.hAlign = "CENTER"
story.append(qa_tbl)
story.append(Spacer(1, 12))
story.append(Paragraph(
    "MyGym - plan the session, log the work, see the progress. All offline.", 
    ParagraphStyle("end", parent=body, alignment=TA_CENTER, textColor=TEXT_MUTED)))

# ---- Build ----
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Calibri", 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 30, "MyGym User Guide")
    canvas.drawRightString(PAGE_W - MARGIN, 30, f"Page {doc.page + 1}")
    canvas.setStrokeColor(BG_SURFACE)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 42, PAGE_W - MARGIN, 42)
    canvas.restoreState()

doc = BaseDocTemplate(
    os.path.join(BASE, "_body.pdf"), pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=54, bottomMargin=56,
    title="MyGym User Guide", author="Z.ai",
)
frame = Frame(MARGIN, 56, CONTENT_W, PAGE_H - 54 - 56, id="main")
doc.addPageTemplates([PageTemplate(id="page", frames=[frame], onPage=on_page)])
doc.build(story)
print("body built:", os.path.join(BASE, "_body.pdf"))
